### PR TITLE
Migrating the JULES User Guide

### LINKED ISSUE #26: Migrating the JULES  User Guide
Migrating the JULES User Guide documentation from Trac to GitHub.

At present, in order to edit and build the User Guide for JULES, developers have to follow the instructions for the doc project which is currently kept in Trac: https://code.metoffice.gov.uk/trac/jules/wiki/BuildingEditingUserGuide 

With the Met Office migrating away from Subversion and Trac to Git and GitHub, this is just one of the first steps in terms of Git migration for JULES.

### PR DESCRIPTION
**Pull request by lianneparkhouse**
Closes #26

### CODE REVIEW

**Comment by lianneparkhouse** [comment]
There's some honing to do here in the repo that I'll add to the backlog (e.g. archiving all of the docs and symlinks from previous releases), but this is a start at getting the JULES User Guide into GitHub. Next step will be circulating mailing/finalising some WPs to let devs know how to make a JULES docs change.

**Review by james-bruten-mo — CHANGES_REQUESTED** [review]
Hi Lianne, I cloned a copy of this repo, then checked out your branch and build the docs with both html and latex. All of the files in the build dirs added by the make script appear to be tracked by git as unstaged for commit? Looking at the top level .gitignore is this because the build paths are starting from the top level? Do the need user_guide/doc in front of them? Similarly, the .idea folder appears in the diff - this probably wants deleting. 

Does this ticket need to be linked with a Jules one deleting the docs there, so there's not 2 places? And do you have updates for https://code.metoffice.gov.uk/trac/jules/wiki/BuildingEditingUserGuide to update the working practices for using git? That page isn't reviewed so long as you're aware we'll need to update it once the changes are up is fine with me.

Cheers

**Comment by lianneparkhouse** [comment]
> Hi Lianne, I cloned a copy of this repo, then checked out your branch and build the docs with both html and latex. All of the files in the build dirs added by the make script appear to be tracked by git as unstaged for commit? Looking at the top level .gitignore is this because the build paths are starting from the top level? Do the need user_guide/doc in front of them? Similarly, the .idea folder appears in the diff - this probably wants deleting.
> 
> Does this ticket need to be linked with a Jules one deleting the docs there, so there's not 2 places? And do you have updates for https://code.metoffice.gov.uk/trac/jules/wiki/BuildingEditingUserGuide to update the working practices for using git? That page isn't reviewed so long as you're aware we'll need to update it once the changes are up is fine with me.
> 
> Cheers

Thanks @james-bruten-mo, looks like the files included in the updated `.gitignore` hadn't been untracked, this should now be working correctly. Do the docs build for you now?

I'll get [jules/wiki/BuildingEditingUserGuide](https://code.metoffice.gov.uk/trac/jules/wiki/BuildingEditingUserGuide) updated once this goes live, and I've also built a wiki for updating the docs in this repo: https://github.com/jules-lsm/jules-lsm.github.io/wiki/Building-and-editing-the-JULES-User-Guide

The thing that's still uncertain at the moment is the location of the JULES Coding Standards, and whether they will live in a centralised repo along with the UMDP3s. I think it might make sense that the JULES Coding Standards are also migrated to here? The FCM docs trunk won't be deleted entirely yet because of this, and also loobos will need a new home. I'll get the JULES ticket ready that just deletes the `user_guide` from FCM for now though.

**Review by james-bruten-mo — APPROVED** [review]
Thanks Lianne, that all looks good now. Built the docs successfully and none of the files are tracked by git. 
The readme wiki looks good and I'll leave you to do something similar with the wiki page.
The coding standards seems like something to decide in future tickets so happy to approve this one now.

**Pull request merged**
